### ISSUE TITLE
Does not work with Tailwind

### ISSUE THREAD

**Issue by mamlzy** [codeskills-dev/responsive-email#8]
I have tried this library, and everything works great until I wrap a Tailwind component, which then breaks. Btw i'm using it with `react-email`

**Comment by gabrielmfern** [comment]
Noticed the same, this might be more of an issue with React Email rather than responsive-email though

**Comment by gabrielmfern** [comment]
This shoudl get fixed by https://github.com/resend/react-email/pull/1536

**Comment by gabrielmfern** [comment]
This can be closed @lordelogos since `@react-email/tailwind@0.0.19-canary.2`

**Comment by lordelogos** [comment]
Closing this as it has been resolved in the new react-email tailwind release
